# -*- coding: utf-8 -*-
"""Copy of Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1URmGmWMVLg_H2NVlKwBg26SSTTJ2j09Y
"""

import pandas as pd

# Load the dataset
heart_failure = pd.read_csv("sample_data/heart_project.txt", sep=",")
heart_failure.head()

#Check for Missing Values
print(heart_failure.isnull().sum())

heart_failure.info()

# Define feature columns and target column
feature_columns = ['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol',
                   'FastingBS', 'RestingECG', 'MaxHR', 'ExerciseAngina',
                   'Oldpeak', 'ST_Slope']
target_column = 'HeartDisease'

# Extract features and target
X = heart_failure[feature_columns]
y = heart_failure[target_column]

from sklearn.model_selection import train_test_split, GridSearchCV

# One-hot encode categorical variables
X = pd.get_dummies(X, drop_first=True)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define parameter grids for SVM and Random Forest
svm_params = {
    'C': [0.01, 0.1, 1, 10, 100, 1000],
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid']
}

rf_params = {
    'n_estimators': [25, 50, 100, 150],
    'max_features': [ 'sqrt', 'log2', None]
}

model = RandomForestClassifier()
model.fit(X_train, y_train)

# predict the mode
y_pred = model.predict(X_test)

# performance evaluation metrics
print(classification_report(y_pred, y_test))

grid_search = GridSearchCV(RandomForestClassifier(),
                           param_grid=rf_params)
grid_search.fit(X_train, y_train)
print(grid_search.best_estimator_)

from sklearn.metrics import accuracy_score
import numpy as np

# Perform Grid Search with cross-validation (5-fold) for SVM
svm_grid = GridSearchCV(SVC(), svm_params, cv=5, scoring='accuracy')
svm_grid.fit(X_train_scaled, y_train)

# Perform Grid Search with cross-validation (5-fold) for Random Forest
rf_grid = GridSearchCV(RandomForestClassifier(random_state=42), rf_params, cv=5, scoring='accuracy')
rf_grid.fit(X_train_scaled, y_train)

# Get the best models from grid search
best_svm = svm_grid.best_estimator_
best_rf = rf_grid.best_estimator_

# Print the best parameters and scores from grid search
print("Best SVM parameters:", svm_grid.best_params_)
print("Best SVM score:", svm_grid.best_score_)
print("Best RF parameters:", rf_grid.best_params_)
print("Best RF score:", rf_grid.best_score_)


# Evaluate the best models on the test set
svm_accuracy = accuracy_score(y_test, best_svm.predict(X_test_scaled))
rf_accuracy = accuracy_score(y_test, best_rf.predict(X_test_scaled))

print(f"SVM Accuracy on test set: {svm_accuracy:.4f}")
print(f"RF Accuracy on test set: {rf_accuracy:.4f}")

import matplotlib.pyplot as plt

# Function to plot decision boundaries (for illustrative purposes only)
def plot_decision_boundary(model, X, y, title):
    h = .02  # Step size in the mesh
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))

    # Predict class for each point in the mesh grid
    Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)

    # Plot the decision boundary and data points
    plt.figure(figsize=(8, 6))
    plt.contourf(xx, yy, Z, alpha=0.8, cmap=plt.cm.Spectral)
    plt.scatter(X[:, 0], X[:, 1], c=y, s=20, edgecolors='k', cmap=plt.cm.Spectral)
    plt.xlabel('Age')
    plt.ylabel('REstingBP')
    plt.title(title)
    plt.show()

# For plotting, we need to preprocess and scale the first two features
X_plot = heart_failure[['Age', 'RestingBP']]
X_train_plot, X_test_plot, y_train_plot, y_test_plot = train_test_split(X_plot, y, test_size=0.25, random_state=42)
X_train_plot_scaled = scaler.fit_transform(X_train_plot)
X_test_plot_scaled = scaler.transform(X_test_plot)

# Train a  SVM and Random Forest model for plotting purposes
modelplot_svm = SVC(C=1,gamma=0.7, kernel='linear').fit(X_train_plot_scaled, y_train_plot)
modelplot_rf = RandomForestClassifier(n_estimators=150, max_features='sqrt', random_state=42).fit(X_train_plot_scaled, y_train_plot)

# Plot decision boundaries for the SVM model
plot_decision_boundary(modelplot_svm, X_train_plot_scaled, y_train_plot, 'SVM Decision Boundary (Age vs. RestingBP)')

# Plot decision boundaries for the Random Forest model
plot_decision_boundary(modelplot_rf, X_train_plot_scaled, y_train_plot, 'Random Forest Decision Boundary (Age vs. RestingBP)')

